### ISSUE TITLE
Portfolio previous and next

### ISSUE THREAD

**Issue by alamont** [orikami-nl/dreamyourwebsite-versie3#2]
Previous jumps to first project. Next works correctly.

**Comment by ThijsvdLaar** [comment]
Fixed, de fout zal hem er in dat de sql statement voor previous het eerste record teruggaf wat kleiner was dan de huidige. Dat is inderdaad altijd het allereerste. Nu geeft hij de laatste terug die kleiner is dan de huidige. (aka de vorige).

**Comment by alamont** [comment]
Awesome! Issues zijn handig!
